#!/bin/bash

cp ./repos/new_linux_scripts/gclient .gclient

cd /repos/src

echo "KALEIDO BUILDER: Setting latest tag and syncing"
git reset --hard
git checkout tags/$CHROMIUM_TAG
gclient sync -D --force --reset
gclient runhooks

# Append kaleido section to headless build file (src/headless/BUILD.gn)
echo "
executable(\"kaleido\") {
  sources = [ \"app/kaleido.cc\" ]

  deps = [
    \":headless_shell_lib\",
    \"//skia\",  # we need this to override font render hinting in headless build
  ]
}" >> headless/BUILD.gn

echo "KALEIDO BUILDER: Installing sysroots"
/repos/src/build/linux/sysroot_scripts/install-sysroot.py --all
